sudo: required
services:
  - docker

before_install:
  - docker build -t gustavoarmelin/docker-react-test -f Dockerfile.dev .

script:
  - docker run gustavoarmelin/docker-react-test npm run test -- --coverage
